#!/usr/bin/env python3
"""
Generate twiddle factor ROM initialization include file for twiddle_rom.v.
Outputs twiddle_init.vh with Verilog initial assignments.

Address map:
  N=256:  addr   0-127    (128 entries, N/2)
  N=1024: addr 128-639   (512 entries, N/2)
  N=4096: addr 640-2687  (2048 entries, N/2)

Each entry is 64 bits: {sin_q24_8[63:32], cos_q24_8[31:0]}
W_N^k = cos(2*pi*k/N) - j*sin(2*pi*k/N)
cos and sin are stored as Q24.8 (multiply float by 256, round, clamp to int32).
"""
import math

def to_q24_8(f):
    v = int(round(f * 256))
    v = max(-0x80000000, min(0x7FFFFFFF, v))
    return v & 0xFFFFFFFF  # unsigned representation for hex output

sizes = [(256, 0), (1024, 128), (4096, 640)]

lines = []
lines.append("// Auto-generated by gen_twiddle.py — do not edit manually")
lines.append("// Format: mem[addr] = {sin_q24_8[63:32], cos_q24_8[31:0]}")
lines.append("")

for N, base in sizes:
    lines.append(f"// N = {N}, addresses {base} to {base + N//2 - 1}")
    for k in range(N // 2):
        angle = 2.0 * math.pi * k / N
        cos_q = to_q24_8(math.cos(angle))
        sin_q = to_q24_8(-math.sin(angle))  # stored as -sin (W = cos - j*sin)
        addr  = base + k
        lines.append(f"        mem[{addr}] = 64'h{sin_q:08X}{cos_q:08X};")
    lines.append("")

out_path = "twiddle_init.vh"
with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"Wrote {out_path} ({sum(N//2 for N,_ in sizes)} entries)")

# Sanity checks
def from_q24_8(u32):
    v = u32 if u32 < 0x80000000 else u32 - 0x100000000
    return v / 256.0

# W_256^0 should be cos=1, sin=0 (addr=0)
cos0 = from_q24_8(to_q24_8(math.cos(0)))
sin0 = from_q24_8(to_q24_8(-math.sin(0)))
assert abs(cos0 - 1.0) < 0.01, f"W_256^0 cos={cos0}"
assert abs(sin0 - 0.0) < 0.01, f"W_256^0 sin={sin0}"

# W_256^64 should be cos=0, sin=1 (addr=64, -sin stored → -1 → W=0-j*sin=0-j*(-(-1))...
# W_N^(N/4) = cos(pi/2) - j*sin(pi/2) = 0 - j*1; stored sin = -(-1) = +... let me recheck
# Actually W_N^(N/4) = exp(-j*pi/2) = -j. cos(pi/2)=0, sin(pi/2)=1.
# stored cos_q = round(0*256)=0, stored sin_q = round(-1*256)=-256
cos_n4 = from_q24_8(to_q24_8(math.cos(math.pi / 2)))
sin_n4 = from_q24_8(to_q24_8(-math.sin(math.pi / 2)))
assert abs(cos_n4 - 0.0) < 0.01, f"W_256^64 cos={cos_n4}"
assert abs(sin_n4 - (-1.0)) < 0.01, f"W_256^64 sin={sin_n4}"

print("Sanity checks passed.")
